eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
                         
server:
  port: 8081      

spring:
  application:
    name: ORDER
env:
  dev
userinfo:
  name: zjx111
  age: 111
