eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
                         
server:
  port: 8081      

spring:
  application:
    name: PROD
env:
  dev
userinfo:
  name: devname229100
  age: 229100
