eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
                         
server:
  port: 8081      

spring:
  application:
    name: PROD
env:
  dev
userInfo:
  name: dev
  age: 19
