eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
                         
server:
  port: 8085     

spring:
  application:
    name: PROD
env:
  test
userinfo:
  name: test
  age: 28
